title: 'Baton Rouge Friends Meeting'
subtitle: 'Bayou Quarterly | South Central Yearly Meeting'
email: 'email@site.com'
description: 'Official website of the Baton Rouge Friends Meeting, a Quaker community in Baton Rouge, Louisiana.'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://garrett-ordner.github.io/brfm-website/' # change to your actual GitHub Pages URL
repository: 'garrett-ordner/brfm-website' # change to your actual repository name
atom_feed:
  hide: true # set to true to hide the feed link in the footer


theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
footer:
  links:
    - label: "Facebook"
      icon: "fab fa-facebook-f"
      url: "https://www.facebook.com/BRFriendsMeeting/"
    
collections:
  pages:
    output: true
    permalink: /:path/



minimal_mistakes_skin: 'dirt'
locale: 'en-US'

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      author_profile: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
